### PR TITLE
Add details for Rook project

### PR DESCRIPTION
**Pull request by xin3liang**
Signed-off-by: Xinliang Liu <xinliang.liu@linaro.org>

### CODE REVIEW

**Comment by xin3liang** [comment]
Seeing below link check error, which has nothing to do with my change?
```
"
1 failed links found:

/Kubernetes/index.html:
   https://v1-18.docs.kubernetes.io/docs/home [404]
Error: Process completed with exit code 1.
"
```

**Comment by martin-g** [comment]
This will be fixed with https://github.com/Linaro/ecosystemlandscape/pull/17

**Comment by xin3liang** [comment]
> This will be fixed with #17

That's great! Any way to recheck after #17 is merged?

**Comment by martin-g** [comment]
Sure! The checks will be executed again after this PR is rebased to `main` after #17 is merged.

**Comment by xin3liang** [comment]
> Sure! The checks will be executed again after this PR is rebased to `main` after #17 is merged.

OK, got it thanks 👍. Hoping #17 merged soon  :smile: @ZhengZhenyu

**Pull request merged**
